#!/usr/bin/env python3
"""Compare an i-jedi NeuralGCM forecast against the reference produced in pure Python.

The reference was generated by stage_neuralgcm_data.py with the same checkpoint, the same
rng seed and the same rollout call, but without going anywhere near C++. The only thing that
differs between the two is the bridge: reading the initial condition through i-jedi's io,
gathering it across MPI tasks, marshalling it to the adapter, and scattering the result back.

That makes this a test of the bridge rather than of NeuralGCM. It is worth having as well as
the usual testref comparison because testref checks three summary numbers per field, and a
summary can survive errors that a field cannot - a hemisphere-flipped temperature field has
very nearly the right minimum, maximum and RMS.

Usage: compare_neuralgcm_forecast.py <forecast.nc> <reference.nc> [--rtol 1e-5]
"""

import argparse
import sys

import numpy as np

try:
    import netCDF4 as nc
except ImportError:
    sys.exit("ERROR: netCDF4 is required")

VARIABLES = [
    "u_component_of_wind",
    "v_component_of_wind",
    "temperature",
    "geopotential",
    "specific_humidity",
    "specific_cloud_liquid_water_content",
    "specific_cloud_ice_water_content",
]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("forecast")
    parser.add_argument("reference")
    parser.add_argument("--rtol", type=float, default=1.0e-5,
                        help="tolerance on max|difference| relative to the field's rms")
    args = parser.parse_args()

    forecast = nc.Dataset(args.forecast)
    reference = nc.Dataset(args.reference)

    print(f"{'variable':40s} {'max|diff|':>12s} {'relative':>10s} {'ref rms':>12s}  result")
    failures = []
    for name in VARIABLES:
        if name not in reference.variables:
            failures.append(f"{name}: absent from the reference")
            continue
        if name not in forecast.variables:
            failures.append(f"{name}: absent from the forecast")
            continue

        a = np.asarray(reference[name][0]).astype(np.float64)
        b = np.asarray(forecast[name][0]).astype(np.float64)
        if a.shape != b.shape:
            failures.append(f"{name}: shape {b.shape} but reference has {a.shape}")
            continue

        diff = float(np.abs(a - b).max())
        rms = float(np.sqrt((a ** 2).mean()))
        relative = diff / rms if rms > 0.0 else diff
        ok = relative <= args.rtol
        print(f"{name:40s} {diff:12.5e} {relative:10.2e} {rms:12.5e}  "
              f"{'ok' if ok else 'FAILED'}")
        if not ok:
            failures.append(f"{name}: relative difference {relative:.2e} exceeds "
                            f"{args.rtol:.1e}")

    print()
    if failures:
        print("FAILED:")
        for failure in failures:
            print(f"  {failure}")
        return 1
    print(f"all {len(VARIABLES)} fields agree with the pure-Python reference "
          f"within {args.rtol:.1e}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
