name: Run all CI tests
on: [pull_request]

jobs:
  run_all_tests:
    runs-on: ubuntu-latest
    name: Full CI (style and tests)
    container: ghcr.io/noaa-emc/i-jedi:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: i-jedi
        submodules: recursive
        ssh-key: ${{ secrets.JCSDA_MIST_KEY }}
    # Checkout mist from jcsda-internal
    - name: checkout-mist
      uses: actions/checkout@v6
      with:
        repository: "JCSDA-internal/mist"
        ref: "feature/install" # Specify your branch here
        path: i-jedi/bundle/mist
        ssh-key: ${{ secrets.JCSDA_MIST_KEY }}
    - name: Run ecbuild
      shell: bash
      run: |
        su - nonroot
        export jedi_cmake_ROOT=/opt/view
        source /opt/spack-environment/activate.sh
        cd $GITHUB_WORKSPACE
        mkdir -p Build
        cd Build
        ecbuild -DMPI_ARGS="--map-by :OVERSUBSCRIBE" -DCLONE_MIST="OFF" ../i-jedi/bundle
        cd ../i-jedi/bundle
    - name: Check container libraries
      id: check-container
      shell: bash
      run: |
        MATCH=true
        if [ -f /opt/jedi/etc/jedi_repo_hashes.txt ]; then
          for d in $GITHUB_WORKSPACE/i-jedi/bundle/*; do
            if [ -d "$d/.git" ]; then
              REPO=$(basename $d)
              if [[ "$REPO" == "ijedi" || "$REPO" == "mist" ]]; then
                continue
              fi
              CURRENT_SHA=$(git -C $d rev-parse HEAD)
              CONTAINER_SHA=$(grep "^$REPO " /opt/jedi/etc/jedi_repo_hashes.txt | cut -d' ' -f2 || true)
              if [ "$CURRENT_SHA" != "$CONTAINER_SHA" ]; then
                echo "$REPO has changed ($CONTAINER_SHA -> $CURRENT_SHA)"
                MATCH=false
              fi
            fi
          done
        else
          echo "No hash file found in container."
          MATCH=false
        fi
        echo "match=$MATCH" >> $GITHUB_OUTPUT
        
        # Also generate a hash for caching if container doesn't match
        HASH=$(find $GITHUB_WORKSPACE/i-jedi/bundle -maxdepth 2 -name .git -type d | sort | xargs -I {} git -C {}/.. rev-parse HEAD | sha256sum | awk '{print $1}')
        echo "hash=$HASH" >> $GITHUB_OUTPUT
    # - name: Cache install of JEDI libraries
    #   if: steps.check-container.outputs.match == 'false'
    #   id: cache-jedi
    #   uses: actions/cache@v5
    #   with:
    #     path: |
    #       ${{ github.workspace }}/install
    #     key: ${{ runner.os }}-jedi-${{ steps.check-container.outputs.hash }}
    - name: Run coding style checks
      shell: bash
      run: |
        su - nonroot
        export jedi_cmake_ROOT=/opt/view
        source /opt/spack-environment/activate.sh
        cd $GITHUB_WORKSPACE/Build/ijedi
        ctest -R coding_norms --output-on-failure
    - name: Compile the code without using container libraries
      if: steps.check-container.outputs.match == 'false'
      shell: bash
      run: |
        su - nonroot
        export jedi_cmake_ROOT=/opt/view
        source /opt/spack-environment/activate.sh
        cd $GITHUB_WORKSPACE
        rm -rf Build
        mkdir -p Build
        cd Build
        ecbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install -DMPI_ARGS="--map-by :OVERSUBSCRIBE" ../i-jedi/bundle 
        make -j4
        make install
    # - name: Compile the code with cache
    #   if: steps.check-container.outputs.match == 'false' && steps.cache-jedi.outputs.cache-hit == 'true'
    #   shell: bash
    #   run: |
    #     su - nonroot
    #     export jedi_cmake_ROOT=/opt/view
    #     source /opt/spack-environment/activate.sh
    #     cd $GITHUB_WORKSPACE
    #     rm -rf Build
    #     chmod +x $GITHUB_WORKSPACE/i-jedi/.github/workflows/fix_circular_dependency.sh
    #     $GITHUB_WORKSPACE/i-jedi/.github/workflows/fix_circular_dependency.sh $GITHUB_WORKSPACE/install $GITHUB_WORKSPACE/i-jedi/bundle/oops
    #     mkdir -p Build
    #     cd Build
    #     ecbuild -DMPI_ARGS="--map-by :OVERSUBSCRIBE" -DBUILD_JEDI=OFF -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/install -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install ../i-jedi/bundle 
    #     cd ijedi
    #     make -j4
    - name: Compile the code with container libraries
      if: steps.check-container.outputs.match == 'true'
      shell: bash
      run: |
        su - nonroot
        export jedi_cmake_ROOT=/opt/view
        source /opt/spack-environment/activate.sh
        cd $GITHUB_WORKSPACE
        rm -rf Build
        mkdir -p Build
        cd Build
        ls -l /opt/jedi
        ls -l /opt/jedi/lib
        ls -l /opt/jedi/include
        ls -l /opt/jedi/bin
        ecbuild -DMPI_ARGS="--map-by :OVERSUBSCRIBE" -DBUILD_JEDI=OFF -DCMAKE_PREFIX_PATH=/opt/jedi -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install ../i-jedi/bundle 
        cd ijedi
        make -j4
    - name: Run ctests
      shell: bash
      run: |
        su - nonroot
        export jedi_cmake_ROOT=/opt/view
        source /opt/spack-environment/activate.sh
        cd $GITHUB_WORKSPACE/Build/ijedi
        export OMPI_ALLOW_RUN_AS_ROOT=1
        export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
        ctest --rerun-failed --output-on-failure --allow-run-as-root
